### ISSUE TITLE
add MODS

### ISSUE THREAD

**Issue by SexyPepsiLOL** [Kappar-Crew/ThermoMekanicalGreg#6]
- top addons
- gregification
- any needed greg addons

**Comment by superhealing** [comment]
if you following close, we have top addons

**Comment by superhealing** [comment]
https://www.curseforge.com/minecraft/mc-mods/gregicality-multiblocks
https://www.curseforge.com/minecraft/mc-mods/devtech
https://www.curseforge.com/minecraft/mc-mods/htmltech

**Comment by SexyPepsiLOL** [comment]
look into the mod GMAN wants us to add. https://github.com/GregTechCEu/Gregification

**Comment by superhealing** [comment]
however, the gregification do not support 2.3.0 if we want to upgrade

**Comment by SexyPepsiLOL** [comment]
ah, i hear 2.3 is gonna be pretty good, so i guess we exclude it

**Comment by superhealing** [comment]
but there is some recent developments, we add for now just don't upgrade
